In [4]:
import pandas as pd

In [5]:
csv = pd.read_csv('data1.csv')

In [6]:
csv

,Unnamed: 0,kind,code,class_name,prof,room_time
0,0,교필,AK00055,비아메디아채플(나와 타인 이해하기),이남호,1505 / 월 / 11:00~11:50
1,1,교필,AK00055,비아메디아채플(리더십의 영성),김한승,3501 / 월 / 11:00~11:50
2,2,교필,AK00055,비아메디아채플(서양음악사),박태영,M301 / 월 / 11:00~11:50
3,3,교필,AK00055,비아메디아채플(성공회이야기),노철래,3301 / 목 / 11:00~11:50
4,4,교필,AK00055,비아메디아채플(시각과 영성),김돈회,M406 / 월 / 11:00~11:50
...,...,...,...,...,...,...
413,413,전선,XE00003,데이터기초수학2,백지현,6206 / 화 / 12:00~13:15\n6206 / 목 / 12:00~13:15
414,414,전선,XE00004,고급머신러닝,홍성준,6405 / 목 / 09:00~11:50
415,415,전선,XE00005,고급Python프로그래밍,홍성준,6405 / 화 / 09:00~11:50
416,416,전선,XE00006,딥러닝프레임워크,이상윤,6405 / 월 / 13:30~14:45\n6405 / 수 / 13:30~14:45
417,417,전선,XE00007,확률과랜덤변수,이상윤,6405 / 월 / 16:30~17:45\n6405 / 수 / 16:30~17:45

In [7]:
type(csv)

pandas.core.frame.DataFrame